apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-basket-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-basket-api
  template:
    metadata:
      labels:
        app: eshop-basket-api
    spec:
      containers:
        - name: eshop-basket-api
          image: joaoneves95/eshop.basket.api:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: CacheSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: eshop-configmap
                  key: eshop-basket-db-redis_connection-string
            - name: ConnectedServicesSettings__DiscountGrpcUrl
              valueFrom:
                configMapKeyRef:
                  name: eshop-configmap
                  key: eshop-discount-grpc_url
            - name: EventBusSettings__HostAddress
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: eshop-shared-rabbitmq_url
