apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-discount-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-discount-grpc
  template:
    metadata:
      labels:
        app: eshop-discount-grpc
    spec:
      containers:
        ###
        - name: eshop-discount-grpc
          image: joaoneves95/eshop.discount.grpc:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: eshop-discount-db-pgsql_connection-string
        ###
        - name: eshop-discount-db-pgsql
          image: postgres
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: eshop-discount-db-pgsql_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: eshop-discount-db-pgsql_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: eshop-configmap
                  key: eshop-discount-db-pgsql_db
        ###
