apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-catalog-api
  template:
    metadata:
      labels:
        app: eshop-catalog-api
    spec:
      containers:
        ###
        - name: eshop-catalog-api
          image: joaoneves95/eshop.catalog.api:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: eshop-catalog-db-mongo_connection-string
        ###
        - name: eshop-catalog-db-mongo
          image: mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: eshop-catalog-db-mongo_user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: eshop-catalog-db-mongo_password
        ###
