apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-catalog-api
  template:
    metadata:
      labels:
        app: eshop-catalog-api
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: appropriate/curl
          command:
            [
              "sh",
              "-c",
              "until curl $(eshop-catalog-db-mongo_connection-string); do echo waiting for mongodb; sleep 2; done;",
            ]
          env:
            - name: eshop-catalog-db-mongo_connection-string
              valueFrom:
                configMapKeyRef:
                  name: eshop-configmap
                  key: eshop-catalog-db-mongo_connection-string
      containers:
        - name: eshop-catalog-api
          image: joaoneves95/eshop-catalog-api
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: eshop-configmap
                  key: eshop-catalog-db-mongo_connection-string
