CREATE DATABASE TodoList;
GO

USE TodoList;

CREATE TABLE dbo.Users (
    User_Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	FirstName NVARCHAR(50) DEFAULT '',
	LastName NVARCHAR(50) DEFAULT '',
);
GO

CREATE TABLE dbo.Gender (
    Gender_Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	GenderName VARCHAR(50) NOT NULL
);
GO

-- CREATE TABLE TodoList.Country

CREATE TABLE dbo.LocalAuth (
    User_Id INT NOT NULL PRIMARY KEY,
	Email NVARCHAR(70) NOT NULL UNIQUE,
	Password NVARCHAR(128) NOT NULL,
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_User_ID_LocalAuth FOREIGN KEY (User_Id) REFERENCES dbo.Users(User_Id)
);
GO

CREATE TABLE dbo.GithubAuth (
    User_Id INT NOT NULL PRIMARY KEY,
	Github_Id NVARCHAR(255) NOT NULL UNIQUE,
	CONSTRAINT FK_User_ID_GithubAuth FOREIGN KEY (User_Id) REFERENCES dbo.Users(User_Id)
);
GO

CREATE TABLE dbo.TwitterAuth (
    User_Id INT NOT NULL PRIMARY KEY,
	Twitter_Id NVARCHAR(255) NOT NULL UNIQUE,
	CONSTRAINT FK_User_ID_TwitterAuth FOREIGN KEY (User_Id) REFERENCES dbo.Users(User_Id)
);
GO

CREATE TABLE dbo.FacebookAuth (
    User_Id INT NOT NULL PRIMARY KEY,
	Facebook_Id NVARCHAR(255) NOT NULL UNIQUE,
	CONSTRAINT FK_User_ID_FacebookAuth FOREIGN KEY (User_Id) REFERENCES dbo.Users(User_Id)
);
GO

CREATE TABLE dbo.Item (
    Item_Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	User_Id INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(User_Id),
	Title NVARCHAR(100) NOT NULL,
	Priority TINYINT NOT NULL,
	Description NVARCHAR(1000) NULL DEFAULT '',
	DueDate DATE NULL DEFAULT '',
	DueTime TIME NULL DEFAULT ''
);
GO
