CREATE DATABASE TodoList;
GO

USE TodoList;

CREATE TABLE dbo.Users (
    User_Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Email NVARCHAR(70) NULL UNIQUE,
	Password NVARCHAR(128) NULL,
	Github_Id NVARCHAR(255) NULL UNIQUE,
	FirstName NVARCHAR(50) DEFAULT '',
	LastName NVARCHAR(50) DEFAULT '',
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	LastLogin DATETIME NULL DEFAULT GETDATE(),
	LoginCount INT NULL DEFAULT 1
);
GO

CREATE TABLE dbo.Gender (
    Gender_Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	GenderName VARCHAR(50) NOT NULL
);
GO

-- CREATE TABLE TodoList.Country

--CREATE TABLE dbo.TwitterAuth (
--    User_Id INT NOT NULL PRIMARY KEY,
--	Twitter_Id NVARCHAR(255) NOT NULL UNIQUE,
--	CONSTRAINT FK_User_ID_TwitterAuth FOREIGN KEY (User_Id) REFERENCES dbo.Users(User_Id)
--);
--GO

--CREATE TABLE dbo.FacebookAuth (
--    User_Id INT NOT NULL PRIMARY KEY,
--	Facebook_Id NVARCHAR(255) NOT NULL UNIQUE,
--	CONSTRAINT FK_User_ID_FacebookAuth FOREIGN KEY (User_Id) REFERENCES dbo.Users(User_Id)
--);
--GO

CREATE TABLE dbo.Item (
    Item_Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	User_Id INT NOT NULL FOREIGN KEY REFERENCES dbo.Users(User_Id),
	Title NVARCHAR(100) NOT NULL,
	Priority TINYINT NOT NULL,
	Description NVARCHAR(1000) NULL DEFAULT '',
	DueDate DATE NULL DEFAULT '',
	DueTime TIME NULL DEFAULT '',
	Created DATETIME NOT NULL DEFAULT GETDATE(),
	LastUpdate DATETIME NOT NULL DEFAULT GETDATE()
);
GO
