[package]
name = "tut_api-actix-cosmosdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "2.7.0"
actix-web = "4.0"
bson = "2.1.0"
futures = "0.3.21"
mongodb = "2.1.0"
