apiVersion: v1
kind: Service
metadata:
  name: eshop-web-app
spec:
  # `NodePort` for localhost.
  type: NodePort
  selector:
    app: eshop-web-app
  ports:
    - protocol: TCP
      port: 30300
      targetPort: 80
      # `nodePort` here is to run locally.
      nodePort: 30300
