apiVersion: v1
kind: Secret
metadata:
  name: eshop-secrets
type: Opaque
stringData:
  eshop-catalog-db-mongo_user: 'admin'
  eshop-catalog-db-mongo_password: 'admin'
  eshop-catalog-db-mongo_connection-string: 'mongodb://admin:admin@127.0.0.1:27017'
  eshop-discount-db-pgsql_user: 'admin'
  eshop-discount-db-pgsql_password: 'admin'
  eshop-discount-db-pgsql_connection-string: 'Host=127.0.0.1;Port=5432;Database=DiscountDb;User ID=admin;Password=admin;'
  eshop-ordering-db-sqlserver_password: '@Admin123456789'
  eshop-ordering-db-sqlserver_connection-string: 'Server=127.0.0.1,1433;Database=master;User Id=sa;Password=@Admin123456789;Trust Server Certificate=True;'
  eshop-ordering-api_email_api-key: '__123456789__'
  eshop-shared-rabbitmq_url: 'amqp://guest:guest@eshop-shared-rabbitmq:5672'
