apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-ordering-db-sqlserver
  labels:
    app: eshop-ordering-db-sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-ordering-db-sqlserver
  template:
    metadata:
      labels:
        app: eshop-ordering-db-sqlserver
    spec:
      containers:
        - name: eshop-ordering-db-sqlserver
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
            - containerPort: 1433
          resources:
            requests:
              memory: "2Gi"
              cpu: "250m"
            limits:
              memory: "2.1Gi"
              cpu: "500m"
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: eshop-ordering-db-sqlserver_password
