apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: eshop.catalog.db.mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop.catalog.db.mongo
  template:
    metadata:
      labels:
        app: eshop.catalog.db.mongo
    spec:
      containers:
        - name: eshop.catalog.db.mongo
          image: mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: eshop.catalog.db.mongo_user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: eshop.catalog.db.mongo_password
